Fix production signature error
I made a mistake when fetching the `first_seen` key. `zrevrange()` returns a list and I need to return only the first element of that list or None. As it was it threw this exception:

```
Traceback (most recent call last):
  File "/Users/mattfaus/dev/webapp/third_party/flask/app.py", line 934, in wsgi_app
    rv = self.dispatch_request()
  File "/Users/mattfaus/dev/webapp/third_party/flask/app.py", line 736, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mattfaus/dev/webapp/api/route_decorator.py", line 122, in no_cache_header_added
    result = func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/route_decorator.py", line 108, in no_sniff_header_added
    result = func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/route_decorator.py", line 86, in api_header_added
    result = func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/route_decorator.py", line 138, in cross_origin_allowed
    result = func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/errors.py", line 76, in api_errors_formatted
    return func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/auth/decorators.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/decorators.py", line 435, in jsonp_enabled
    val = func(*args, **kwargs)
  File "/Users/mattfaus/dev/webapp/api/decorators.py", line 307, in wrapper
    transformed_result = func_sig.transform(result, 'response')
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 330, in transform
    source_value, '%s["%s"]' % (display_name, field_key.name))
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 184, in transform
    for i, elem in enumerate(obj)
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 330, in transform
    source_value, '%s["%s"]' % (display_name, field_key.name))
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 709, in transform
    return self.sig.transform(obj, display_name)
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 730, in transform
    _validate_type(obj, display_name, self.expected_type)
  File "/Users/mattfaus/dev/webapp/api/sig.py", line 160, in _validate_type
    raise SignatureError(message)
SignatureError: Expected response["errors"][0]["firstSeen"] to have type <type 'basestring'>, but was <type 'list'> (value [u'20150427_16']).
```

Test Plan:
Deploy and hit /devadmin/errors again to see it not return the above exception.

Auditors: tom